### ISSUE TITLE
docker build failing

### ISSUE THREAD

**Issue by dgonyeo** [tweag/sparkle#112]
The docker build has started failing due to:

```
Can't exec "bash": No such file or directory at /root/.nix-profile/bin/nix-shell line 313.
```

The automated build [fails with this error](https://hub.docker.com/r/tweag/sparkle/builds/b8bhojk62qbeecj5e3xfe9a/), and when I attempt to build the image locally I run into the same issue.

I'm having problems using sparkle due to this because my host has stack 1.5.1 and `tweag/sparkle:latest` on the Docker hub has stack 1.5.0.

The base image for sparkle, `tweag/stack-docker-nix`, has already been updated to have stack 1.5.1.

The setup here is a little beyond me, so if someone is able to get this building again that would be awesome.

**Comment by mboes** [comment]
@regnat could you look into this and resolve it?

**Comment by regnat** [comment]
This is probably due to the fact that [this commit](https://github.com/NixOS/nix/commit/1511f01351c992b2b5b3108e6f1854bac50df71d#diff-e7970290dcf5a2d5cb830c5173b49245) removed bash from the `nixos/nix` image (I don't know why I didn't hit this when testing locally, I probably used an older cached version of the image).

I'll push a fix including back bash to `tweag/stack-docker-nix` as soon as I'm able to build locally to confirm that adding `bash` back fixes it (which can take some time, my internet connection is flaky these days, so it may be tomorrow morning).

@dgonyeo re:the stack versions mismatch, I tend to use stack with the  `--docker-stack-exe download` arguments which re-downloads stack (in the correct version) in the image and avoids these incompatibilities issues.

**Comment by regnat** [comment]
This is probably due to the fact that [this commit](https://github.com/NixOS/nix/commit/1511f01351c992b2b5b3108e6f1854bac50df71d#diff-e7970290dcf5a2d5cb830c5173b49245) removed bash from the `nixos/nix` image (I don't know why I didn't hit this when testing locally, I probably used an older cached version of the image).

I'll push a fix including back bash to `tweag/stack-docker-nix` as soon as I'm able to build locally to confirm that adding `bash` back fixes it.

@dgonyeo re:the stack versions mismatch, I tend to use stack with the  `--docker-stack-exe download` arguments which re-downloads stack (in the correct version) in the image and avoids these incompatibilities issues.

**Comment by regnat** [comment]
I've added bash back to the `tweag/stack-docker-nix` image and it seems to fix the build failure.

@mboes I don't have the rights do do it myself, but I think the build of the `sparkle` image has to be manually retriggered on dockerhub

**Comment by regnat** [comment]
(actually using `--docker-stack-exe download` may not work until tweag/stack-docker-nix#9 is merged)

**Comment by mboes** [comment]
> I think the build of the sparkle image has to be manually retriggered on dockerhub

The builds on Dockerhub are configured to trigger rebuilds of downstream Docker images. I just had a look at the logs and it's telling me that images were rebuilt a couple of hours ago for all of `stack-docker-nix`, `inline-java` and `sparkle`.

**Comment by dgonyeo** [comment]
I just confirmed this isn't happening anymore. Closing.
