### ISSUE TITLE
Use Get<PrimitiveType>ArrayElementsCritical instead of Get<PrimitiveType>ArrayElements

### ISSUE THREAD

**Issue by alpmestan** [tweag/sparkle#17]
Get<PrimitiveType>ArrayElements may or may not provide us with a copy of an object (whether/when it does is implementation defined). If it doesn't, then I think we'll be suffering from races no matter what we do here, unless we lock the object. The problem is that some other Java thread could be modifying the array concurrently to us copying the array to a mutable Haskell vector, to be frozen once done.

With GetPrimitiveArrayCritical, the JVM takes a lock, and disables GC to avoid the data being moved anywhere. So we can use that to copy the data off quickly to a buffer under GHC control, and then unsafeFreeze that atomically.

OTOH one could argue that we shouldn't be pessimimistically locking anything - that the same pitfalls arise in Java in general. IOW it's the programmer's responsibility to synchronize access if an object is likely to be mutated concurrently. So this task is up for discussion.

**Comment by mboes** [comment]
As the original author of this ticket (and its last paragraph), and having thought about this some more, I'm inclined to say concurrency isn't the issue. We use `Get<*>ArrayElements` in reification. Based on the rationale of the last paragraph, I don't see a need for `*Critical` there. @alpmestan agreed?

The only other argument for using `*Critical` is to avoid fragmentation of the Java heap, because if the JVM doesn't hand us a copy of a buffer it'll have to be pinned in memory. But arguably that's again the JVM's problem, which is free to hand us a copy if it likes in order to avoid fragmentation (some JVM implementations, such as IBM's, systematically do so). And in this case, the better solution is to use `Get<*>ArrayRegion`.

**Comment by alpmestan** [comment]
Sounds good to me, the case for the `*Critical` functions isn't strong enough at this point.
