### ISSUE TITLE
Gradle build fails because of IllegalAccessException

### ISSUE THREAD

**Issue by mgajda** [tweag/sparkle#41]
I tried to `stack install`, and then `gradle build` from current repo, and got the following error on Ubuntu 16.04 (and OpenJDK 8):
```
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 57 more
Caused by: java.lang.IllegalAccessException: class org.gradle.internal.reflect.DirectInstantiator cannot access class com.sun.tools.javac.api.JavacTool (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @68d8ae27
	at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:49)
	... 82 more
```

It seems to happen in `:compileJava` task:
```
Execution failed for task ':compileJava'.
> Could not create an instance of type com.sun.tools.javac.api.JavacTool.
```

**Comment by mboes** [comment]
Hm, can't reproduce using openjdk 8, and searching the string for the error leads me to [plenty of hits involving JDK 9 and Gradle](https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=Caused+by%3A+java.lang.IllegalAccessException%3A+class+org.gradle.internal.reflect.DirectInstantiator+cannot+access+class+com.sun.tools.javac.api.JavacTool+(in+module+jdk.compiler)+because+module+jdk.compiler+does+not+export+com.sun.tools.javac.api+to+unnamed+module). What precise version are you using?

**Comment by mboes** [comment]
See https://github.com/gradle/gradle/blob/master/design-docs/jdk9-support.md. Apparently JDK 9 is introducing some kind of new module system, described as a "breaking change" in the ecosystem. Gradle doesn't yet support JDK 9 (but it hasn't been released yet). I'm surprised that you would get any such error using JDK 8, which to my knowledge doesn't have Jigsaw.

**Comment by mgajda** [comment]
Indeed that may be OpenJDK 9 issue, but if it is, then the following `.stack/config.yaml` was insufficient to prevent gradle from choosing wrong version:
```
extra-include-dirs:
  - /usr/lib/jvm/java-8-openjdk-amd64/include
  - /usr/lib/jvm/java-8-openjdk-amd64/include/linux
extra-lib-dirs:
  - /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server
```

I had to remove all `openjdk-9-*` package from my _Ubuntu 16.04_ system before the build started to work. Then `stack` build failed to find `*.h` files, so I used the following commands and Cabal:
```bash
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre/
export C_INCLUDE_PATH="/usr/lib/jvm/java-8-openjdk-amd64/include:/usr/lib/jvm/java-8-openjdk-amd64/include/linux"
export LD_LIBRARY_PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server
cabal install --extra-lib-dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server
```

**Comment by mboes** [comment]
`extra-{include,lib}-dirs` does just what the name says: adds extra paths to the search set. Using `stack --nix` is the preferred way in this project to make sure the build uses exactly the JVM versions we expect and to avoid this kind of system dependence. Setting the `LD_LIBRARY_PATH` as you do should work the same for `cabal install` and for `stack`. Best thing to do I think is to add a new entry to the FAQ about current non-compat between jdk 9 and Gradle (since it's a special case, seeing as JDK upgrades don't normally introduce breaking changes).
