### ISSUE TITLE
Fail to build sparkle due to preprocessing issue

### ISSUE THREAD

**Issue by abailly** [tweag/sparkle#42]
I am trying to `$ stack build` sparkle and it chokes while building `inline-java`:

```
$ stack build
Warning: File listed in inline-java/inline-java.cabal file does not exist: src/Foreign/JNI.c
Warning: File listed in sparkle.cabal file does not exist: build/libs/sparkle.jar
inline-java-0.1: build
Progress: 1/5
--  While building package inline-java-0.1 using:
      /Users/arnaud/.stack/setup-exe-cache/x86_64-osx/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.5.0 build lib:inline-java --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/arnaud/projects/sparkle/.stack-work/logs/inline-java-0.1.log

    Preprocessing library inline-java-0.1...
    [2 of 3] Compiling Foreign.JNI      ( src/Foreign/JNI.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/Foreign/JNI.o )
    
    /Users/arnaud/projects/sparkle/inline-java/src/Foreign/JNI.hs:290:1:
        Invalid type signature: call Void Method :: Coercible o (J a) =>
                                                    o -> JMethodID -> [JValue] -> IO ()
        Should be of form <variable> :: <type>
```

What am I doing wrong?

**Comment by mboes** [comment]
Looks like your CPP preprocessor is behaving differently from that on Travis CI and on our machines. Line 290 should be defining a function called `callVoidMethod`. We do so via CPP, because it's easier and more readable than doing it via TH (and TH wouldn't give us meaningful extra static guarantees in this case). See the definition for `CALL_METHOD` just above that line.

Now to understand why your CPP is behaving differently...

One workaround of course is to `stack --nix build`, because that will use the same CPP as the rest of us do (you'll need Nix installed on your system first). You'll get better build reproducibility that way. That said we'd like to continue supporting non-nix builds.

BTW - noticed you're on OS X. See #12 - it's not a supported platform as of yet. You'll have far better luck on a Linux VM. (in any case if you build a binary on OS X you'll only be able to run it on OS X Spark clusters...)

**Comment by abailly** [comment]
Thanks for the quick reply. FWIW the output from `cpphs` is fine... I will try to build it in a linux env then. Here is some more info on my cpp which might or might not be helpful...

```
$ cpp --version
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```
