### ISSUE TITLE
What region is the example tweag-sparkle S3 bucket in?

### ISSUE THREAD

**Issue by nh2** [tweag/sparkle#47]
Amazon EMR seems to allow me to access only S3 buckets from the same region, otherwise I get:

```
Exception in thread "main" com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.model.AmazonS3Exception: Moved Permanently (Service: Amazon S3; Status Code: 301; Error Code: 301 Moved Permanently; Request ID: 95CED38D10227342), S3 Extended Request ID: BFdd3gEqXuBBFj/ukdTMavB/Oq9OfoYxNMBui4s0IfClwAC/i91dduFuE1UrSWSw4xg1znCFq+s=
```

for each sparkle example. What region is the `tweag-sparkle` S3 bucket in?

**Comment by mboes** [comment]
I take it from #48 that this issue is now resolved?

**Comment by nh2** [comment]
I'm not sure, as the other blog post simply has a different data source. If I want to try the examples that are in the repo, I still need to know where the bucket is (I think) in order to spawn my cluster there.

**Comment by mboes** [comment]
I'm surprised that this is the case, since that particular S3 bucket is in fact public, and can be downloaded just fine when running on a local machine that's not even in Amazon's cloud. Do you have a detailed repro?

FYI here's the metadata for that bucket as it stands today:

```
Bucket:	tweag-sparkle
Region:	US Standard
Creation Date:	Tue Feb 23 20:11:50 GMT+100 2016
```

I think US Standard means US East (or at any rate is a superset).
